# Generated by Django 5.0.4 on 2024-05-04 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
