# Generated by Django 5.0.4 on 2024-05-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0002_alter_permisos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
    ]
