# Generated by Django 5.0.4 on 2024-05-04 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0003_alter_permisos_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='campo_prueba',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
