# Generated by Django 5.0.4 on 2024-05-04 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0005_permisos_campo_prueba_2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='campo_prueba',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='campo_prueba_2',
        ),
        migrations.AlterField(
            model_name='modulos',
            name='descripcion',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='estado',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='modulos',
            name='nombre',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='descripcion',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_modulos',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aysu.modulos'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='aysu.tipousuario'),
        ),
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='descripcion',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='tipousuario',
            name='nombre',
            field=models.CharField(default=None, max_length=30, unique=True),
        ),
    ]
