# Generated by Django 5.0.4 on 2024-05-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0006_remove_permisos_campo_prueba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modulos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
