# Generated by Django 5.0.4 on 2024-05-04 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0007_alter_modulos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='nombre',
        ),
    ]
