# Generated by Django 5.0.4 on 2024-05-04 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0008_remove_permisos_descripcion_remove_permisos_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permisos',
            old_name='id_modulos',
            new_name='modulos_id',
        ),
        migrations.RenameField(
            model_name='permisos',
            old_name='id_tipo_usuario',
            new_name='tipo_usuario_id',
        ),
    ]
