# Generated by Django 5.0.4 on 2024-05-04 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aysu', '0009_rename_id_modulos_permisos_modulos_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permisos',
            name='modulos_id',
        ),
        migrations.RemoveField(
            model_name='permisos',
            name='tipo_usuario_id',
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_modulos',
            field=models.ForeignKey(db_column='id_modulos', default=None, on_delete=django.db.models.deletion.CASCADE, to='aysu.modulos'),
        ),
        migrations.AddField(
            model_name='permisos',
            name='id_tipo_usuario',
            field=models.ForeignKey(db_column='id_tipo_usuario', default=None, on_delete=django.db.models.deletion.CASCADE, to='aysu.tipousuario'),
        ),
    ]
